version: "3"

services:
  postgres:
    image: postgres:11.5-alpine
    container_name: blog_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/posgresql/data/

volumes:
  postgres_db:


